"""Regression tests for the slop-detector and concept-classifier noise fixes.

Each test pins one specific false-positive pattern we just removed:

  * generated files don't trip ``weak_implementation`` / ``copy_paste_noise``;
  * vitest-browser-react's ``expect.element(...)`` registers as an assertion;
  * tiny test-file diffs no longer trigger ``test file has scenario shape
    but no assertions``;
  * ``_authenticated`` no longer matches the ``auth_check`` concept;
  * the synthesizer's auto-block threshold is the new ``>= 90`` (and an
    81-score PR with zero block-severity findings stays in ``review``).
"""
from __future__ import annotations

import importlib.util
import unittest
from pathlib import Path
from typing import Any


def _load_agent_module(rel_path: str, module_name: str) -> Any:
    """Import an agent's main.py without putting its src/ on sys.path."""
    here = Path(__file__).resolve().parents[1]
    spec = importlib.util.spec_from_file_location(module_name, here / rel_path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


slop = _load_agent_module(
    "agents/slop-detector/src/slop_detector/main.py",
    "slop_detector_main_under_test",
)
concept = _load_agent_module(
    "agents/concept-classifier/src/concept_classifier/main.py",
    "concept_classifier_main_under_test",
)
synthesizer = _load_agent_module(
    "agents/truth-report-synthesizer/src/truth_report_synthesizer/main.py",
    "truth_report_synthesizer_main_under_test",
)


# ---------------------------------------------------------------------------
# slop-detector: generated files don't get the weak/copy-paste/etc. treatment
# ---------------------------------------------------------------------------


class SlopDetectorGeneratedFileGuardTest(unittest.TestCase):
    def test_generated_file_with_route_registrations_is_not_weak(self) -> None:
        """A TanStack routeTree.gen.ts diff used to fire weak_implementation
        because each ``as any`` cast looks like a placeholder. With the guard
        in place, generated files only ever emit ``generated_churn`` —
        and only past the size threshold."""
        small_routetree_patch = (
            "@@ -0,0 +1,5 @@\n"
            "+/* eslint-disable */\n"
            "+// @ts-nocheck\n"
            "+// This file was automatically generated by TanStack Router.\n"
            "+const AuthenticatedReleaseHighlightsRoute = (route as any)\n"
            "+const AuthenticatedRoute = (route as any)\n"
        )
        result = slop.inspect_file(
            {
                "path": "src/routeTree.gen.ts",
                "additions": 5,
                "changes": 5,
                "classification": "generated",
                "patch": small_routetree_patch,
            },
            raw_file={"patch": small_routetree_patch},
        )
        # Small generated diff with no real signals → no slop finding at all.
        self.assertIsNone(result)

    def test_huge_generated_churn_still_flagged(self) -> None:
        result = slop.inspect_file(
            {
                "path": "pnpm-lock.yaml",
                "additions": 600,
                "changes": 700,
                "classification": "generated",
                "patch": "@@\n" + "\n".join(f"+entry_{i}: value" for i in range(50)),
            },
            raw_file={"patch": "@@\n" + "\n".join(f"+entry_{i}" for i in range(50))},
        )
        self.assertIsNotNone(result)
        self.assertIn("generated_churn", result["categories"])  # type: ignore[index]


# ---------------------------------------------------------------------------
# slop-detector: assertion patterns + tightened weak_test threshold
# ---------------------------------------------------------------------------


class SlopDetectorAssertionPatternsTest(unittest.TestCase):
    def test_vitest_browser_expect_element_counts_as_assertion(self) -> None:
        patch = (
            "@@ -0,0 +1,12 @@\n"
            "+describe('ReleaseHighlightsSection', () => {\n"
            "+  it('renders cards', async () => {\n"
            "+    const screen = await render(<ReleaseHighlightsSection />)\n"
            "+    await expect.element(screen.getByText('Hello')).toBeInTheDocument()\n"
            "+    await expect.element(screen.getByText('World')).toBeInTheDocument()\n"
            "+  })\n"
            "+  it('filters', async () => {\n"
            "+    const screen = await render(<ReleaseHighlightsSection />)\n"
            "+    await userEvent.click(screen.getByText('Filter'))\n"
            "+    await expect.element(screen.getByText('Filtered')).toBeInTheDocument()\n"
            "+  })\n"
            "+})\n"
        )
        result = slop.inspect_file(
            {
                "path": "src/features/release-highlights/components/release-highlights-section.test.tsx",
                "additions": 12,
                "changes": 12,
                "classification": "test",
                "patch": patch,
            },
            raw_file={"patch": patch},
        )
        # Tests with real chained-expect assertions should NOT flag weak_test.
        if result is not None:
            self.assertNotIn("weak_test", result.get("categories", []))

    def test_to_be_in_the_document_counts_as_assertion(self) -> None:
        # Whole-word matchers like ``toBeInTheDocument`` couldn't match the old
        # ``\bto(Be|…)\b`` rule. The new ``.\s*toBe…\(`` rule does.
        patch = (
            "@@ -0,0 +1,8 @@\n"
            "+describe('thing', () => {\n"
            "+  it('renders', () => {\n"
            "+    const el = render(<X />)\n"
            "+    el.getByText('hi').toHaveTextContent('hi')\n"
            "+    el.getByText('hi').toHaveBeenCalled()\n"
            "+    el.getByText('hi').toBeInTheDocument()\n"
            "+  })\n"
            "+})\n"
        )
        text = "\n".join(line[1:] for line in patch.splitlines() if line.startswith("+"))
        added = [line[1:] for line in patch.splitlines() if line.startswith("+")]
        self.assertIsNone(
            slop.test_slop_signal("src/foo.test.tsx", text, added),
            "modern matcher call patterns should count as assertions",
        )

    def test_tiny_test_diff_does_not_flag_weak_test(self) -> None:
        """The user's 4-line ``{ exact: true }`` patch to search-provider.test.tsx
        used to flag weak_test because the patch text contained ``describe(``
        from context lines but no full ``expect(`` literal. With both the
        broader assertion patterns AND the added-line threshold, small,
        targeted test edits stop being flagged."""
        patch = (
            "@@ -70,3 +70,3 @@\n"
            " describe('Search', () => {\n"
            "-    await expect.element(getByText('Light')).toBeInTheDocument()\n"
            "+    await expect.element(getByText('Light', { exact: true })).toBeInTheDocument()\n"
            " })\n"
        )
        result = slop.inspect_file(
            {
                "path": "src/context/search-provider.test.tsx",
                "additions": 1,
                "changes": 2,
                "classification": "test",
                "patch": patch,
            },
            raw_file={"patch": patch},
        )
        if result is not None:
            self.assertNotIn("weak_test", result.get("categories", []))


# ---------------------------------------------------------------------------
# concept-classifier: token-aware matching for single-word terms
# ---------------------------------------------------------------------------


class ConceptClassifierTokenMatchingTest(unittest.TestCase):
    def test_underscore_authenticated_does_not_match_auth_check(self) -> None:
        findings = concept.classify_concepts(
            {
                "path": "src/routes/_authenticated/release-highlights/index.tsx",
                "classification": "logic",
                "risk_score": 24,
                "risk_reasons": ["classified as logic"],
                "symbols": [{"name": "Route"}],
            },
            {
                "patch": (
                    "@@ -0,0 +1,3 @@\n"
                    "+import { createFileRoute } from '@tanstack/react-router'\n"
                    "+import { ReleaseHighlights } from '@/features/release-highlights'\n"
                    "+export const Route = createFileRoute('/_authenticated/release-highlights/')\n"
                ),
                "content": "",
            },
        )
        concepts = [f["concept"] for f in findings]
        self.assertNotIn("auth_check", concepts)

    def test_real_session_token_still_matches_auth_check(self) -> None:
        """The fix must not over-correct: an actual ``session`` / ``token``
        token in the diff should still fire ``auth_check``."""
        findings = concept.classify_concepts(
            {
                "path": "src/auth/session.ts",
                "classification": "logic",
                "risk_score": 30,
                "risk_reasons": ["classified as logic"],
                "symbols": [{"name": "buildSession"}],
            },
            {
                "patch": (
                    "@@ -0,0 +1,2 @@\n"
                    "+function buildSession() {\n"
                    "+  const token = readToken(); return token\n"
                    "+}\n"
                ),
                "content": "",
            },
        )
        concepts = [f["concept"] for f in findings]
        self.assertIn("auth_check", concepts)

    def test_phrase_term_still_uses_substring(self) -> None:
        """Multi-word / punctuated terms (``"fetch("``, ``"system message"``)
        must keep working via substring — they're not word-shaped, so the
        token branch wouldn't help them."""
        findings = concept.classify_concepts(
            {
                "path": "src/api/client.ts",
                "classification": "logic",
                "risk_score": 25,
                "risk_reasons": [],
                "symbols": [{"name": "callApi"}],
            },
            {
                "patch": (
                    "@@ -0,0 +1,2 @@\n"
                    "+async function callApi() {\n"
                    "+  return fetch('/api/thing')\n"
                    "+}\n"
                ),
                "content": "",
            },
        )
        self.assertIn("external_http_call", [f["concept"] for f in findings])


# ---------------------------------------------------------------------------
# synthesizer status escalation threshold
# ---------------------------------------------------------------------------


class StatusEscalationThresholdTest(unittest.TestCase):
    """The synthesizer used to flip to ``blocked`` at ``risk_score >= 80``
    even without any block-severity finding. That's how the user's
    release-highlights PR ended up Blocked with ``Blockers: 0``. New rule
    is ``>= 90`` so review-required noise can't auto-block."""

    def _run_minimal(self, *, risk_from_compression: float) -> dict[str, Any]:
        payload = {
            "pull_request": {"body": ""},
            "changed_files": [],
            "prior_results": {
                "review-compression": {
                    "output": {
                        "risk_score": int(risk_from_compression),
                        "risk_score_raw": risk_from_compression,
                        "hotspots": [],
                        "must_inspect": [],
                        "safe_to_skim": [],
                        "owner_summary": [],
                        "hotspot_themes": [],
                    }
                },
                "intent-extractor": {"output": {"intent_items": []}},
                "evidence-mapper": {"output": {"evidence_links": [], "missing_evidence_findings": []}},
                "semantic-diff-explainer": {"output": {"behavioral_deltas": [], "blast_radius": []}},
                "policy-gate": {"output": {"policy_findings": []}},
                "prompt-canary": {"output": {"prompt_findings": [], "prompt_canary_runs": []}},
                "contract-comparator": {"output": {"contract_findings": [], "suggested_tests": []}},
                "slop-detector": {"output": {"slop_findings": [], "remove_candidates": [], "rework_candidates": []}},
                "semantic-evidence-agent": {"output": {"memory_findings": []}},
                "test-coverage-validator": {"output": {"coverage_findings": [], "coverage_status": "ok", "coverage_matrix": []}},
                "concept-classifier": {"output": {"concept_findings": []}},
            },
        }
        result = synthesizer.run(payload)
        return result["output"]["summary"]

    def test_compression_risk_81_no_blockers_stays_in_review(self) -> None:
        summary = self._run_minimal(risk_from_compression=81.0)
        # Score saturates so display will be ~81; with no findings, status
        # must stay "review" instead of auto-escalating to "blocked".
        self.assertEqual(summary["status"], "review")

    def test_catastrophic_risk_still_blocks_without_explicit_finding(self) -> None:
        summary = self._run_minimal(risk_from_compression=200.0)
        # Raw 200 saturates near 100 (the curve asymptotes). >=90 should
        # still escalate — we keep a safety net for runaway scores.
        self.assertGreaterEqual(summary["risk_score"], 90)
        self.assertEqual(summary["status"], "blocked")


if __name__ == "__main__":
    unittest.main()
