from __future__ import annotations

import unittest

from packages.core.analysis_utils import (
    GENERATED_HEADER_RE,
    has_paired_test,
    is_generated,
    is_static_data_file,
    risk_hits_in_added_lines,
    saturate_risk,
)


class RiskKeywordTokenizationTest(unittest.TestCase):
    """Phase-1: substring matches like `_authenticated -> auth` should NOT fire,
    but camelCase identifiers SHOULD still surface their constituent tokens."""

    def test_underscore_authenticated_no_longer_matches_auth(self) -> None:
        patch = (
            "@@\n"
            "+export const Route = createFileRoute('/_authenticated/release-highlights/')\n"
            "+import { ReleaseHighlights } from '@/features/release-highlights'\n"
        )
        self.assertEqual(risk_hits_in_added_lines(patch), [])

    def test_authentication_word_does_not_match_auth(self) -> None:
        patch = "@@\n+// Authentication subsystem documentation lives in docs.\n"
        self.assertEqual(risk_hits_in_added_lines(patch), [])

    def test_camelcase_charge_gateway_matches_charge(self) -> None:
        patch = "@@\n+await chargeGateway.refund(request.paymentId)\n"
        hits = risk_hits_in_added_lines(patch)
        # Order follows RISK_KEYWORDS list.
        self.assertIn("payment", hits)
        self.assertIn("refund", hits)
        self.assertIn("charge", hits)

    def test_snake_case_auth_token_still_matches(self) -> None:
        patch = "@@\n+const auth_token = request.session.token\n"
        hits = risk_hits_in_added_lines(patch)
        self.assertIn("auth", hits)
        self.assertIn("token", hits)


class GeneratedDetectionTest(unittest.TestCase):
    def test_path_pattern_catches_tanstack_route_tree(self) -> None:
        self.assertTrue(is_generated("src/routeTree.gen.ts"))

    def test_path_pattern_catches_protobuf(self) -> None:
        self.assertTrue(is_generated("packages/api/refund_pb2.py"))

    def test_header_marker_catches_handwritten_path(self) -> None:
        content = (
            "// @generated by openapi-typescript-codegen\n"
            "export interface Refund {}\n"
        )
        self.assertTrue(is_generated("src/openapi/types.ts", content))

    def test_regular_source_file_is_not_generated(self) -> None:
        self.assertFalse(is_generated("src/features/release-highlights/index.tsx"))

    def test_header_regex_matches_common_markers(self) -> None:
        for marker in (
            "// Code generated by protoc-gen-go. DO NOT EDIT.",
            "# AUTO-GENERATED FILE",
            "/* @generated */",
            "// Auto generated by openapi-codegen",
        ):
            self.assertIsNotNone(
                GENERATED_HEADER_RE.search(marker),
                msg=f"expected marker to match: {marker!r}",
            )


class PairedTestDetectionTest(unittest.TestCase):
    def test_section_test_pairs_with_section_source(self) -> None:
        self.assertTrue(
            has_paired_test(
                "src/features/release-highlights/components/release-highlights-section.tsx",
                [
                    "src/features/release-highlights/components/release-highlights-section.test.tsx",
                ],
            )
        )

    def test_spec_suffix_also_pairs(self) -> None:
        self.assertTrue(has_paired_test("src/foo.ts", ["src/foo.spec.ts"]))

    def test_unrelated_test_does_not_pair(self) -> None:
        self.assertFalse(
            has_paired_test("src/foo.ts", ["src/bar.test.ts"])
        )

    def test_empty_test_list_returns_false(self) -> None:
        self.assertFalse(has_paired_test("src/foo.ts", []))


class StaticDataDetectionTest(unittest.TestCase):
    def test_static_export_in_data_directory_is_static(self) -> None:
        patch = (
            "@@\n"
            "+export const highlights = [\n"
            "+  { id: 'a', title: 'A' },\n"
            "+  { id: 'b', title: 'B' },\n"
            "+]\n"
        )
        self.assertTrue(
            is_static_data_file("src/features/release-highlights/data/highlights.ts", patch)
        )

    def test_function_definition_disqualifies_static(self) -> None:
        patch = (
            "@@\n"
            "+export function filterHighlights(items, audience) {\n"
            "+  return items.filter((h) => h.audience === audience)\n"
            "+}\n"
        )
        self.assertFalse(
            is_static_data_file("src/features/release-highlights/data/highlights.ts", patch)
        )

    def test_path_outside_data_directory_does_not_qualify(self) -> None:
        patch = "@@\n+export const Foo = [1, 2, 3]\n"
        self.assertFalse(is_static_data_file("src/features/foo/index.ts", patch))

    def test_json_file_qualifies_even_without_patch(self) -> None:
        self.assertTrue(is_static_data_file("config/users.json"))


class SaturatingCurveTest(unittest.TestCase):
    """Phase-3: scores 0..knee are linear; above knee the curve asymptotes
    toward 100, so very-high raw values still differentiate."""

    def test_zero_in_zero_out(self) -> None:
        self.assertEqual(saturate_risk(0), 0)

    def test_linear_below_knee(self) -> None:
        self.assertEqual(saturate_risk(40), 40)
        self.assertEqual(saturate_risk(80), 80)

    def test_monotonic_above_knee(self) -> None:
        sample = [saturate_risk(x) for x in (90, 120, 160, 220, 500)]
        for left, right in zip(sample, sample[1:]):
            self.assertLessEqual(left, right, msg=f"curve is not monotonic: {sample}")

    def test_bounded_at_100(self) -> None:
        self.assertLessEqual(saturate_risk(10_000), 100)
        self.assertGreaterEqual(saturate_risk(1_000), 99)

    def test_negative_input_clamps_to_zero(self) -> None:
        self.assertEqual(saturate_risk(-5), 0)


if __name__ == "__main__":
    unittest.main()
