from __future__ import annotations

import math
import re
from fnmatch import fnmatch
from pathlib import PurePosixPath
from typing import Any


RISK_KEYWORDS = [
    "auth",
    "authorize",
    "token",
    "payment",
    "billing",
    "refund",
    "charge",
    "pii",
    "email",
    "sql",
    "migration",
    "retry",
    "timeout",
    "prompt",
    "secret",
    "agent",
    "webhook",
]

SOURCE_SUFFIXES = {".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"}
TEST_MARKERS = ("/test/", "/tests/", "/__tests__/", ".test.", ".spec.", "_test.py")
PROMPT_PATTERNS = ("prompts/**", "agents/**", "**/*.prompt.md", "**/*.prompt", "**/*.jinja", "**/*.tmpl")
GENERATED_PATTERNS = (
    "*.lock",
    "*.snap",
    "dist/**",
    "build/**",
    "**/__generated__/**",
    "**/*.min.js",
    "**/*.gen.*",
    "**/*_pb2.py",
    "**/*_pb2.pyi",
    "**/*.pb.go",
    "**/routeTree.gen.*",
)

# Header markers commonly inserted by code generators (only checked against the
# first ~1 KB of file content). Catches generated files whose path doesn't match
# the patterns above — e.g. a vendored proto bundle or a hand-named .ts file
# carrying an `@generated` banner.
GENERATED_HEADER_RE = re.compile(
    r"(?:auto[-\s]?generated|code\s+generated\s+by|do\s+not\s+edit|@generated)",
    re.IGNORECASE,
)

# Split a string on non-letters AND on camelCase / PascalCase boundaries so
# `paymentId` -> {payment, id}, `chargeGateway` -> {charge, gateway},
# `URLPattern` -> {url, pattern}. Used to make risk-keyword matching robust
# to camelCase identifiers without devolving to substring matching (which
# tagged `_authenticated` as `auth`).
_TOKEN_SPLIT_RE = re.compile(r"[^A-Za-z]+|(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")


def normalize_path(path: str) -> str:
    return str(PurePosixPath(str(path).replace("\\", "/")))


def language_for(path: str) -> str:
    suffix = PurePosixPath(path).suffix.lower()
    return {
        ".py": "python",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".js": "javascript",
        ".jsx": "javascript",
        ".md": "markdown",
        ".json": "json",
        ".yaml": "yaml",
        ".yml": "yaml",
    }.get(suffix, "unknown")


def is_generated(path: str, content: str = "") -> bool:
    """Detect auto-generated files via filename glob OR a generator header banner.

    Path patterns catch the common cases (`*.gen.*`, `*_pb2.py`, lockfiles, etc.).
    The header check catches vendored bundles and hand-named files that carry
    `@generated` / `Code generated by` / `DO NOT EDIT` banners — only the first
    1 KB is scanned to keep this cheap.
    """
    clean = normalize_path(path)
    if any(fnmatch(clean, pattern) for pattern in GENERATED_PATTERNS):
        return True
    if content and GENERATED_HEADER_RE.search(content[:1024]):
        return True
    return False


def is_test(path: str) -> bool:
    clean = f"/{normalize_path(path).lower()}"
    return any(marker in clean for marker in TEST_MARKERS)


def is_prompt(path: str) -> bool:
    clean = normalize_path(path)
    return any(fnmatch(clean, pattern) for pattern in PROMPT_PATTERNS)


def is_docs(path: str) -> bool:
    clean = normalize_path(path).lower()
    return clean.startswith("docs/") or clean.endswith((".md", ".mdx", ".rst", ".txt"))


def tokenize(text: str) -> set[str]:
    """Lower-case token set, split on non-letters AND camelCase boundaries.

    Used by ``risk_hits*`` and downstream agents (concept-classifier, inline
    anchors) so a substring of a longer identifier (the classic
    `_authenticated` matching `auth` problem) no longer fires the keyword,
    while still letting `chargeGateway` / `customerEmail` register the
    `charge` / `email` keywords they genuinely contain.
    """
    return {tok.lower() for tok in _TOKEN_SPLIT_RE.split(text) if tok}


# Back-compat alias for callers that imported the underscore-prefixed name
# while it was internal. New code should use ``tokenize``.
_tokenize = tokenize


def risk_hits(*parts: str) -> list[str]:
    """Token-aware risk match across the supplied text parts (path, patch, content).

    Kept for backwards compat with callers that pass already-narrowed text.
    Prefer ``risk_hits_in_added_lines`` for diff-driven classification —
    matching on the path alone gives false positives (e.g., flagging files
    just because they import from ``_authenticated/``).
    """
    tokens: set[str] = set()
    for part in parts:
        if part:
            tokens.update(tokenize(str(part)))
    return [keyword for keyword in RISK_KEYWORDS if keyword in tokens]


def added_patch_lines(patch: str) -> list[str]:
    """Return only the lines added in a unified diff (no ``+++``/headers)."""
    out: list[str] = []
    for raw in (patch or "").splitlines():
        if raw.startswith("+++") or raw.startswith("---") or raw.startswith("@@"):
            continue
        if raw.startswith("+"):
            out.append(raw[1:])
    return out


def risk_hits_in_added_lines(patch: str, content: str = "") -> list[str]:
    """Stricter risk match: scan only the ADDED diff lines (+ optional file content).

    Deliberately ignores the file path so a clean component file under
    ``src/routes/_authenticated/...`` doesn't get tagged "auth-touching" just
    because the directory name contains ``auth``. Likewise a UI helper that
    imports from a module named ``token-store`` won't trip "token" unless
    the helper actually writes the word ``token`` in its added lines.

    Uses token-aware matching (see ``tokenize``) so identifiers like
    ``_authenticated`` no longer match the bare ``auth`` keyword.
    """
    body = "\n".join(added_patch_lines(patch))
    if content:
        body = f"{body}\n{content}"
    if not body:
        return []
    tokens = tokenize(body)
    return [keyword for keyword in RISK_KEYWORDS if keyword in tokens]


# ---------------------------------------------------------------------------
# Scoring helpers used by the risk-score pipeline.
# ---------------------------------------------------------------------------


def saturate_risk(raw: float, knee: float = 80.0, span: float = 40.0) -> int:
    """Map an uncapped raw risk number into the 0-100 display range.

    Linear for ``raw <= knee``, then asymptotes toward 100 with an exponential
    decay of width ``span``. Lets us preserve precision in the "normal" risk
    range while still differentiating very-high scores via the persisted raw
    value — instead of the previous hard ``min(100, x)`` cap that flattened
    every high-risk PR to the same number.

    Examples (knee=80, span=40):
        raw=40  -> 40
        raw=80  -> 80
        raw=100 -> 88
        raw=150 -> 96
        raw=400 -> 100
    """
    value = max(0.0, float(raw))
    if value <= knee:
        return int(round(value))
    headroom = max(0.0, 100.0 - knee)
    return int(round(knee + headroom * (1.0 - math.exp(-(value - knee) / max(1.0, span)))))


# File-name pairing for "did the author also touch the test for this file?"
_TEST_SUFFIX_RE = re.compile(r"\.(?:test|spec)\.[a-z]+$", re.IGNORECASE)


def has_paired_test(file_path: str, test_paths: list[str]) -> bool:
    """True iff ``test_paths`` contains a test file that plausibly covers ``file_path``.

    Matches if any test path's filename stem (after stripping ``.test``/``.spec``)
    equals the source file's stem. No AST analysis — same-stem heuristic.
    """
    clean = normalize_path(file_path)
    stem = PurePosixPath(clean).stem
    if not stem:
        return False
    for test_path in test_paths:
        if not test_path:
            continue
        norm_test = normalize_path(test_path)
        test_stem = _TEST_SUFFIX_RE.sub("", PurePosixPath(norm_test).name)
        if test_stem == stem:
            return True
    return False


# Identifiers that signal a file is "code", not static literal data.
_CODE_MARKERS_RE = re.compile(
    r"\b(?:function|class|def|async\s+def|=>\s*[{(]|await\s|return\s+[A-Za-z_(])",
)


def is_static_data_file(path: str, patch: str = "") -> bool:
    """Heuristic: the file looks like an exported literal dataset, not logic.

    Triggers when EITHER the path lives under a ``data/`` directory OR the file
    has a tabular suffix (``.json``, ``.yaml``), AND the added lines contain no
    function-shaped code markers. Used to give back a small risk credit for
    files like ``src/features/release-highlights/data/highlights.ts`` that are
    pure ``export const`` arrays.
    """
    clean = normalize_path(path).lower()
    suffix = PurePosixPath(clean).suffix
    path_signal = (
        "/data/" in f"/{clean}"
        or clean.startswith("data/")
        or "/fixtures/" in f"/{clean}"
        or suffix in {".json", ".yaml", ".yml"}
    )
    if not path_signal:
        return False
    added = "\n".join(added_patch_lines(patch))
    if not added.strip():
        # No diff hints — fall back to the path signal alone, which is already
        # restrictive (``data/`` directory or JSON/YAML suffix).
        return True
    return not _CODE_MARKERS_RE.search(added)


def important_terms(text: str) -> list[str]:
    words = re.sub(r"[^a-zA-Z0-9_/-]+", " ", text).lower().split()
    stop = {"that", "this", "with", "from", "into", "should", "must", "need", "needs", "review"}
    return [word for word in words if len(word) >= 4 and word not in stop][:16]


def extract_symbols(path: str, patch: str = "", content: str = "") -> list[dict[str, Any]]:
    source = "\n".join(part for part in [patch, content] if part)
    patterns = [
        ("class", re.compile(r"^[+\s]*(?:export\s+)?class\s+([A-Za-z_$][\w$]*)", re.M)),
        ("function", re.compile(r"^[+\s]*(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)", re.M)),
        ("function", re.compile(r"^[+\s]*(?:export\s+)?const\s+([A-Za-z_$][\w$]*)\s*=", re.M)),
        ("function", re.compile(r"^[+\s]*(?:async\s+)?def\s+([A-Za-z_][\w]*)", re.M)),
    ]
    symbols: list[dict[str, Any]] = []
    seen: set[str] = set()
    for kind, pattern in patterns:
        for match in pattern.finditer(source):
            name = match.group(1)
            key = f"{kind}:{name}"
            if key in seen:
                continue
            seen.add(key)
            symbols.append({"name": name, "kind": kind, "confidence": 0.82})
    if symbols:
        return symbols
    return [{"name": PurePosixPath(path).stem, "kind": "file", "confidence": 0.42}]


def codeowners_for(path: str, codeowners: str = "") -> list[str]:
    clean = normalize_path(path)
    matches: list[tuple[int, list[str]]] = []
    for raw in codeowners.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        pattern, *owners = line.split()
        normalized_pattern = pattern.lstrip("/")
        if normalized_pattern.endswith("/"):
            hit = clean.startswith(normalized_pattern)
        else:
            hit = fnmatch(clean, normalized_pattern) or clean.startswith(f"{normalized_pattern.rstrip('/')}/")
        if hit and owners:
            matches.append((len(normalized_pattern.replace("*", "")), owners))
    if not matches:
        return ["unassigned"]
    return sorted(matches, key=lambda item: item[0], reverse=True)[0][1]
